app/users/urls.py
from django.urls import path

from app.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from app.events.views import EventListView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", EventListView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("app.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # events app urls
    path("event/", include("app.events.urls", namespace="events")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

app/users/models.py
from django.contrib.auth.models import AbstractUser, UserManager as BaseUserManager
from django.db import models
from django.urls import reverse


class UserManager(BaseUserManager):
    # pylint: disable=arguments-differ
    def _create_user(self, username, email, password, **extra_fields):
        """[summary]
        Create and save a user with the given username, email, and password.
        """

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        return super().create_user("", email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return super().create_superuser("", email, password, **extra_fields)


class User(AbstractUser):
    """[summary]
    User Model

    Extended from the AbstractUser of Django
    """

    username = None  # type: ignore
    email = models.EmailField("Email", blank=True, unique=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []  # type: ignore

    class Meta:
        ordering = ["email"]
        verbose_name = "User"
        verbose_name_plural = "Users"
        db_table = "users"

    def __str__(self):
        return f"{self.email}"

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"pk": self.pk})

    @property
    def is_email_verified(self):
        return self.emailaddress_set.filter(email=self.email, verified=True).exists()  # type: ignore

    @property
    def event_created(self):
        return self.owner.all()

    @property
    def screen_name(self):
        return self.email.split("@")[0]

    @property
    def participated_events(self):
        return self.participants.all()

app/users/forms.py
from .models import User
from django.contrib.auth import forms as auth_forms


class UserChangeForm(auth_forms.UserChangeForm):
    """[summary]
    UserChangeForm -> User Update

    User update his data
    """

    class Meta:
        model = User
        fields = "__all__"


class UserCreationForm(auth_forms.UserCreationForm):
    """[summary]
    UserCreationForm -> User Create

    Create user account
    """

    class Meta:
        model = User
        fields = ("email",)

app/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    """[summary]
    UserDetailView -> User Profile

    User view his data

    url: /users/<int:pk>/
    pk = user.id
    """

    model = User


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """[summary]
    UserUpdateView -> User update

    User update his data

    url: /users/~update/
    """

    model = User
    fields = [
        "email",
    ]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.id})

    def get_object(self):
        return User.objects.get(id=self.request.user.id)  # type: ignore

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    """[summary]
    url: /users/~update/
    """

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.id})


user_redirect_view = UserRedirectView.as_view()

app/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}


{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
    <br>
      <h2>{{ object.name }}</h2>
      {% if object.email %}
        <p>Email: {{ object.email }}</p>
      {% endif %}
      <p>Screen Name: {{object.screen_name}}</p>
      <p>Events Created:</p>
      {% for event in object.event_created %}
      <ul>
        <li> {{ event.title }} --- {{ event.date }} ---> <a class="btn btn-primary" href="{{ event.get_absolute_url }}" role="button"
        >Event Detail</a></li>
      </ul>
      {% endfor %}
      <p>Participated Events:</p>
      {% for event in object.participated_events %}
      <ul>
        <li> {{ event.title }} --- {{ event.date }} ---> <a class="btn btn-primary" href="{{ event.get_absolute_url }}" role="button"
        >Event Detail</a></li>
      </ul>
      {% endfor %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">Email</a>
    <a class="btn btn-primary" href="{% url "account_reset_password" %}" role="button">Reset Password</a>
    <a class="btn btn-primary" href="{% url "account_change_password" %}" role="button">Change Password</a>
    <a class="btn btn-primary" href="{% url 'account_logout'%}" role="button">Signout</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>

<br>
<hr>

<div class="row">

  <div class="col-sm-12">
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

app/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}