app/events/urls.py
from django.urls import path
from .views import (
    EventDetailView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    AddParticipant,
)

app_name = "events"

urlpatterns = [
    path("<int:pk>", EventDetailView.as_view(), name="event"),
    path("update/<int:pk>/", EventUpdateView, name="update"),
    path("delete/<int:pk>/", EventDeleteView, name="delete"),
    path("addparticipant/<int:pk>/", AddParticipant, name="addparticipant"),
    path("add/", EventCreateView.as_view(), name="add"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from app.events.views import EventListView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", EventListView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("app.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # events app urls
    path("event/", include("app.events.urls", namespace="events")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

app/events/models.py
import datetime
from django.db import models
from django.urls import reverse
from app.users.models import User


class Event(models.Model):
    """[summary]
    Event Model
    """

    owner = models.ForeignKey(
        User, related_name="owner", on_delete=models.PROTECT, blank=True, null=True
    )
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    date = models.DateField()
    participants = models.ManyToManyField(User, "participants", blank=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"
        db_table = "events"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("events:event", kwargs={"pk": self.id})

    @property
    def count_participants(self):
        return self.participants.count()

    @property
    def screen_name(self):
        return self.owner.email.split("@")[0]  # type: ignore

    @property
    def participants_users(self):
        return self.participants.all()

    @property
    def done_event(self):
        return self.date < datetime.date.today()

app/events/forms.py
from django import forms
from .models import Event


class DateInput(forms.DateInput):
    """[summary]
    Add usable date field to the form
    """

    input_type = "date"


class EventForm(forms.ModelForm):
    """[summary]
    Event Add / update form
    """

    class Meta:
        model = Event
        fields = ["title", "description", "date"]
        widgets = {"date": DateInput()}

app/events/views.py
import datetime
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Event
from .forms import EventForm


class EventListView(ListView):
    """[summary]
    EventListView -> Event List

    List all events data
    Paginated 5

    url: /
    """

    model = Event
    paginate_by = 5
    ordering = ["-date"]
    template_name = "pages/home.html"


class EventDetailView(DetailView):
    """[summary]
    EventDetailView -> Event Detail

    Event detail

    url: /event/<int:pk>/
    pk = event.id
    """

    model = Event
    template_name = "pages/event.html"


class EventCreateView(LoginRequiredMixin, CreateView):
    """[summary]
    EventCreateView -> Event Create

    Create new Event

    url: /event/add/
    """

    model = Event
    template_name = "pages/add_event.html"
    form_class = EventForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        title = form.cleaned_data["title"]
        date = form.cleaned_data["date"]
        today = datetime.date.today()
        if date < today:
            messages.error(self.request, f"Event date must be in the future")
            return redirect("events:add")
        messages.success(
            self.request, f"You Created event {title} that will happen in {date}"
        )
        return super().form_valid(form)


@login_required
def AddParticipant(request, pk):
    """[summary]
    AddParticipant

    User can goto to Event
    User can Ignore Event

    url: addparticipant/<int:pk>/
    pk = event.id
    """

    event = get_object_or_404(Event, id=pk)
    participated = event.participants.filter(id=request.user.id)
    if event.done_event:
        messages.warning(
            request, f"Sorry, {event.title} is already take place in {event.date}"
        )
        return redirect("home")

    if participated:
        event.participants.remove(request.user)
        messages.warning(request, f"You withdrawed {event.title}")
    else:
        event.participants.add(request.user)
        messages.success(
            request, f"You are going to {event.title} that will happen in {event.date}"
        )
    return redirect("home")


@login_required
def EventUpdateView(request, pk):
    """[summary]
    EventUpdateView -> Event Update

    Update new Event

    url: /event/update/<int:pk>/
    pk = event.id
    """

    event = Event.objects.get(id=pk)
    if request.user != event.owner:
        return redirect("events:add")

    context = {}
    obj = get_object_or_404(Event, id=pk)
    form = EventForm(request.POST or None, instance=obj)
    if form.is_valid():
        date = form.cleaned_data["date"]
        today = datetime.date.today()
        if date < today:
            messages.error(request, f"Event date must be in the future")
            return redirect("events:update", pk=pk)
        form.save()
        return HttpResponseRedirect("/")
    context["form"] = form
    template_name = "pages/edit_event.html"
    messages.success(request, f"You Updated {event.title}")
    return render(request, template_name, context)


@login_required
def EventDeleteView(request, pk):
    """[summary]
    EventDeleteView -> Event Delete

    Update new Event

    url: /event/delete/<int:pk>/
    pk = event.id
    """

    event = Event.objects.get(id=pk)
    if request.user != event.owner:
        return redirect("events:add")

    context = {}  # type: ignore
    event = get_object_or_404(Event, id=pk)
    if request.method == "POST":
        event.delete()
        return HttpResponseRedirect("/")
    template_name = "pages/event_delete.html"
    messages.warning(request, f"You Going to Deleted {event.title}")
    return render(request, template_name, context)

app/templates/pages/about.html
{% extends "base.html" %}

app/templates/pages/add_event.html
{% extends "base.html" %} {% block content %}
<h1>Add Event</h1>
<form method="post" class="card-body">
  <div class="md-form mb-5">
    {% csrf_token %} {{ form.as_p }}
    <button
      class="btn btn-primary btn-lg btn-block"
      type="submit"
      value="Submit"
    >
      Add
    </button>
  </div>
</form>
{% endblock content %}

app/templates/pages/edit_event.html
{% extends "base.html" %} {% block content %}
<h1>Edit Event</h1>
<form method="post" class="card-body">
  <div class="md-form mb-5">
    {% csrf_token %} {{ form.as_p }}
    <button
      class="btn btn-primary btn-lg btn-block"
      type="submit"
      value="Submit"
    >
      Add
    </button>
  </div>
</form>
{% endblock content %}

app/templates/pages/event.html
{% extends "base.html" %} {% block content %}

<h1>Event Detail Page</h1>

<li>Event Name: {{ event.title }} - Date: {{ event.date }}</li>
<ul>
  <li>Event Creator: {{ event.screen_name }}</li>
  <li>Event Description: {{ event.description }}</li>
  <li>Amount of Participants: {{ event.count_participants }}</li>

  <br />

  {% if request.user.is_authenticated and request.user.id is event.owner.id%}
  <a
    class="btn btn-primary"
    href="{% url 'events:update' event.id %}"
    role="button"
    >Update Event</a
  >
  <a
    class="btn btn-primary"
    href="{% url 'events:delete' event.id %}"
    role="button"
    >Delete Event</a
  >
  {% endif %} 
  {% if request.user.is_authenticated %}
  {% if request.user in event.participants_users %}
  {%if not event.done_event%}
  <a
    class="btn btn-primary"
    href="{% url 'events:addparticipant' event.id %}"
    role="button"
    >Ignore</a
  >
  {% else %}
  <a
    class="btn btn-primary"
    href="{% url 'events:addparticipant' event.id %}"
    role="button"
    >Going</a
  >
  {% endif %}
  {% endif %}
  {% endif %}
</ul>

{% endblock content %}

app/templates/pages/event_confirm_delete.html
{% extends "base.html" %} {% block content %}
<h1>Event Delete</h1>
<form method="post">
  {% csrf_token %} Are you sure you want to delete?

  <button class="btn btn-primary btn-lg btn-block" type="submit" value="Submit">
    Delete
  </button>
</form>
{% endblock content %}

app/templates/pages/event_delete.html
{% extends "base.html" %} {% block content %}
<h1>Event Delete</h1>
<form method="post">
  {% csrf_token %} Are you sure you want to delete?

  <button class="btn btn-primary btn-lg btn-block" type="submit" value="Submit">
    Delete
  </button>
</form>
{% endblock content %}

app/templates/pages/event_form.html
{% extends "base.html" %} {% block content %}
<h1>Event Edit</h1>
<form method="post" class="card-body">
  <div class="md-form mb-5">
    {% csrf_token %} {{ form.as_p }}
    <button
      class="btn btn-primary btn-lg btn-block"
      type="submit"
      value="Submit"
    >
      Add
    </button>
  </div>
</form>
{% endblock content %}

app/templates/pages/home.html
{% extends "base.html" %} {% block content %}
<h1>Event List</h1>
<br />
{% for event in page_obj%}
<li>Event Name: {{ event.title }} - Date: {{ event.date }}</li>
<ul>
  <li>Event Creator: {{ event.screen_name }}</li>
  <li>Amount of Participants: {{ event.count_participants }}</li>
  <a class="btn btn-primary" href="{{ event.get_absolute_url }}" role="button"
    >Event Detail</a
  >
</ul>
{% endfor %}

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
  </span>
</div>

{% endblock content %}